import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '@/providers';

//page import
import CardComponent from '@/components/CardComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex flex-col h-screen w-full '>
          <div className='w-screen h-[10%] '></div> {/* Header */}
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
